<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Office Name Aliases
    |--------------------------------------------------------------------------
    |
    | Use this when an office changes name, acronym, or spelling but should
    | still be treated as the same office in graphs and year-to-year analytics.
    |
    | Format:
    |   'OLD OR ALTERNATIVE NAME' => 'ONE STABLE CANONICAL OFFICE NAME',
    |
    | Add future renamed offices here instead of changing old WFP records.
    |
    */
    'aliases' => [
        'OVPAA' => 'OFFICE OF THE VICE PRESIDENT FOR ACADEMIC AFFAIRS',
        'OFFICE OF THE VICE PRESIDENT FOR ACADEMIC AFFAIRS' => 'OFFICE OF THE VICE PRESIDENT FOR ACADEMIC AFFAIRS',

        'OVPREP' => 'OFFICE OF THE VICE PRESIDENT FOR RESEARCH, EXTENSION, AND PRODUCTION',
        'OFFICE OF THE VICE PRESIDENT FOR RESEARCH, EXTENSION, AND PRODUCTION' => 'OFFICE OF THE VICE PRESIDENT FOR RESEARCH, EXTENSION, AND PRODUCTION',

        'OVPAF' => 'OFFICE OF THE VICE PRESIDENT FOR ADMINISTRATION AND FINANCE',
        'OFFICE OF THE VICE PRESIDENT FOR ADMINISTRATION AND FINANCE' => 'OFFICE OF THE VICE PRESIDENT FOR ADMINISTRATION AND FINANCE',

        'RESEARCH' => 'RESEARCH DIVISION',
        'RESEARCH DIVISION' => 'RESEARCH DIVISION',

        'EXTENSION' => 'EXTENSION DIVISION',
        'EXTENSION DIVISION' => 'EXTENSION DIVISION',

        'EXECUTIVE' => 'PRESIDENTIAL AFFAIRS DIVISION',
        'EXECUTIVE AFFAIRS' => 'PRESIDENTIAL AFFAIRS DIVISION',
        'PRESIDENTIAL AFFAIRS DIVISION' => 'PRESIDENTIAL AFFAIRS DIVISION',

        'FINANCE' => 'FINANCE SERVICES DIVISION',
        'FINANCE SERVICES OFFICE' => 'FINANCE SERVICES DIVISION',
        'FINANCE SERVICES DIVISION' => 'FINANCE SERVICES DIVISION',

        'ADMINISTRATIVE' => 'ADMINISTRATIVE SERVICES DIVISION',
        'ADMINISTRATIVE SERVICES' => 'ADMINISTRATIVE SERVICES DIVISION',
        'ADMINISTRATIVE SERVICES DIVISION' => 'ADMINISTRATIVE SERVICES DIVISION',

        'QAO' => 'QUALITY ASSURANCE DIVISION',
        'QUALITY ASSURANCE OFFICE' => 'QUALITY ASSURANCE DIVISION',
        'QUALITY ASSURANCE DIVISION' => 'QUALITY ASSURANCE DIVISION',

        'OSDS' => 'STUDENT DEVELOPMENT AND SERVICES DIVISION',
        'OFFICE OF THE STUDENT DEVELOPMENT SERVICES' => 'STUDENT DEVELOPMENT AND SERVICES DIVISION',
        'STUDENT DEVELOPMENT AND SERVICES DIVISION' => 'STUDENT DEVELOPMENT AND SERVICES DIVISION',

        'PRMO' => 'INSTITUTIONAL PLANNING AND PROJECT DEVELOPMENT DIVISION',
        'PLANNING AND RESOURCE MANAGEMENT OFFICE' => 'INSTITUTIONAL PLANNING AND PROJECT DEVELOPMENT DIVISION',
        'INSTITUTIONAL PLANNING AND PROJECT DEVELOPMENT DIVISION' => 'INSTITUTIONAL PLANNING AND PROJECT DEVELOPMENT DIVISION',

        'CURRICULUM' => 'CURRICULUM AND INSTRUCTION DIVISION',
        'CURRICULUM AND INSTRUCTION DIVISION' => 'CURRICULUM AND INSTRUCTION DIVISION',

        'IADS' => 'INSTITUTE OF ADVANCED STUDIES',
        'INSTITUTE OF ADVANCE STUDIES' => 'INSTITUTE OF ADVANCED STUDIES',
        'INSTITUTE OF ADVANCED STUDIES' => 'INSTITUTE OF ADVANCED STUDIES',

        'IC' => 'INSTITUTE OF COMPUTING',
        'INSTITUTE OF COMPUTING' => 'INSTITUTE OF COMPUTING',

        'ILEGG' => 'INSTITUTE OF LEADERSHIP, ENTREPRENEURSHIP, AND GOOD GOVERNANCE',
        'INSTITUTE OF LEADERSHIP, ENTREPRENEURSHIP, AND GOOD GOVERNANCE' => 'INSTITUTE OF LEADERSHIP, ENTREPRENEURSHIP, AND GOOD GOVERNANCE',

        'ITED' => 'INSTITUTE OF TEACHER EDUCATION',
        'INSTITUTE OF TEACHER EDUCATION' => 'INSTITUTE OF TEACHER EDUCATION',

        'IAAS' => 'INSTITUTE OF AQUATIC AND APPLIED SCIENCES',
        'INSTITUTE OF AQUATIC AND APPLIED SCIENCES' => 'INSTITUTE OF AQUATIC AND APPLIED SCIENCES',
    ],

    'skip_patterns' => [
        'SOME OF THE OFFICES',
        'TO HAVE AN EFFECTIVE TRACING',
        'REFERENCES',
        'CY 20',
        'PERFORMANCE INDICATORS',
    ],
];
